services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      # MySQL système occupe déjà 3306 → on expose le MySQL Docker sur 3307
      - "3307:3306"
###< doctrine/doctrine-bundle ###

###> elasticsearch ###
  elasticsearch:
    ports:
      - "9200:9200"
###< elasticsearch ###

###> redis ###
  redis:
    ports:
      - "6379:6379"
###< redis ###
